services:
  prometheus-volume-init:
    image: alpine:latest
    container_name: prometheus-volume-init
    command: ["sh", "-c", "chown -R 65534:65534 /prometheus/data && echo 'Prometheus data volume permissions set.'"]
    volumes:
      - prometheus-data:/prometheus/data
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.49.0
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      prometheus-volume-init:
        condition: service_completed_successfully
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus/data
      - --web.enable-admin-api
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus/data
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    restart: unless-stopped
    pid: "host"
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
    networks:
      - monitoring

  thanos-sidecar:
    image: thanosio/thanos:v0.36.1
    container_name: thanos-sidecar
    restart: unless-stopped
    depends_on:
      - prometheus
    command:
      - sidecar
      - --tsdb.path=/prometheus/data
      - --prometheus.url=http://prometheus:9090
      - --http-address=0.0.0.0:19191
      - --grpc-address=0.0.0.0:10901
    volumes:
      - prometheus-data:/prometheus/data:ro
      - ./thanos/bucket.yaml:/etc/thanos/bucket.yaml:ro
    ports:
      - "19191:19191"
      - "10901:10901"
    networks:
      - monitoring

  thanos-query:
    image: thanosio/thanos:v0.36.1
    container_name: thanos-query
    restart: unless-stopped
    depends_on:
      - thanos-sidecar
    command:
      - query
      - --http-address=0.0.0.0:19090
      - --grpc-address=0.0.0.0:19091
      - --store=thanos-sidecar:10901
    ports:
      - "19090:19090"
      - "19091:19091"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SERVER_HTTP_ADDR: "0.0.0.0"
      GF_SERVER_HTTP_PORT: "2000"
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD:-admin}"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/provisioning/alerting:/etc/grafana/provisioning/alerting:ro
      - ./grafana/provisioning/plugins:/etc/grafana/provisioning/plugins:ro
      - ./grafana/dashboards:/etc/grafana/dashboards:ro
    ports:
      - "2000:2000"
    depends_on:
      - prometheus
      - thanos-query
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
