{
 "title": "Sigil",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Dynamic Engagement Score",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sigil_dynamic_engagement_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Engagement Δ WoW",
   "type": "stat",
   "description": "Engagement Change vs 7d ago\n(Will not populate until a sufficient history is available)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sigil_engagement_wow_change", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Mean Session Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sigil_session_duration_seconds_sum[$__range]))\n/\nsum(increase(sigil_session_duration_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Regional Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Current Players by Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sigil_players_by_region", "legendFormat": "{{region}}" }
   ]
  },
  {
   "title": "Active Regions over Time",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum by (region) (sigil_players_by_region)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sigil Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Concurrent Players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 29 },
   "targets": [
    { "expr": "sigil_active_sessions", "legendFormat": "Players" }
   ]
  },
  {
   "title": "Session Duration Percentiles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.25,\n  sum by (le) (\n    increase(sigil_session_duration_seconds_bucket[$__range])\n  )\n)\n",
     "legendFormat": "P25"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    increase(sigil_session_duration_seconds_bucket[$__range])\n  )\n)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum by (le) (\n    increase(sigil_session_duration_seconds_bucket[$__range])\n  )\n)",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    increase(sigil_session_duration_seconds_bucket[$__range])\n  )\n)",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}